# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restauantlocation_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestauantLocation',
            new_name='RestaurantLocation',
        ),
    ]
