# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='excludes',
            field=models.TextField(blank=True, help_text='Separate each item by comma', null=True),
        ),
    ]
